Visma-Consulting/formula

CHANGELOG.md
src/configToSchemas/types/form.js
src/useNormalizeConfig/maybeSetElements.js
src/useResolveElementReferences.js

- Move conversion to an earlier step (normalize config)
- Also optimize resolving element references

Fix processing form group elements in legacy mode

---

CHANGELOG.md
src/api.js

- Convert number id to string, to correctly trigger refetch

Fix refetching when revision changes:

---

lang/en-US.json
lang/sv-SE.json
src/Review/index.js

Add aria-label to print-button

---

src/configToSchemas/typePlugins/autocomplete.js
src/configToSchemas/typePlugins/selectAutocomplete.js

Fix duplicate labels in autocomplete

---

src/configToSchemas/types/number.js

Set default undefined in some cases

---

lang/en-US.json
lang/sv-SE.json
src/Review/types/object.js
src/configToSchemas/types/tableField.js

Table field accessibility fixes

---

src/useLocalize.js

KEHFORM-617

---

src/Review/index.js

KEHFORM-384

---

src/configToSchemas/types/multiselect.js

Disable choices

---

lang/en-US.json
lang/sv-SE.json
src/useLocalizeErrors.js

Add missing errormessages

---

src/ConfirmDialog.js
src/withConfirmSubmit.js

Submit spinner

---

lang/en-US.json
lang/sv-SE.json
src/useLocalizeErrors.js

KEHFORM-619

---

src/configToSchemas/types/tableField.js

Missing form label

---

src/withConfirmSubmit.js

Change try-catch to then-catch

---

src/configToSchemas/commonPlugins/repeatableFieldSupport.js

Make default array as long as minItems

---

lang/en-US.json
lang/sv-SE.json
src/configToSchemas/types/number.js

Reverts Visma-Consulting/formula#53

Revert "Fix/allow decimal rename number field"

---

src/configToSchemas/types/multiselect.js

No disables in filter dialog

---

src/useDynamicElements.js

Filtering for pageTitle

---

src/useDynamicElements.js

Indentation for filtered fields

---

src/Review/types/boolean.js
src/configToSchemas/types/boolean.js

No selection boolean

---

src/Formula.js
src/useDynamicElements.js

No adding indent to pageTitles

---

api.json
src/api.js
src/withConfirmSubmit.js
src/withPrefill/withLoader.js

Add actionId for submit and resubmit when available

---

src/configToSchemas/types/consent.js

Käytetään booleanissa olevia mappauksia suostumus kentälle

KEHFORM-626

---

src/Review/types/string.js
src/configToSchemas/types/range.js
src/useLocalizeConfig.js

Slider labels

---

lang/en-US.json
lang/sv-SE.json
src/configToSchemas/types/consent.js
src/useLocalizeErrors.js

Suostumus kentän validoinnin virheteksti

KEHFORM-806

---

src/withSteps.js

Fix scrolling when no title

---

lang/en-US.json
lang/sv-SE.json
src/configToSchemas/types/boolean.js
src/configToSchemas/types/multiselect.js
src/configToSchemas/types/select.js

Radionappulat ja valintalaatikot rivissä

---

src/withSteps.js

Paluu takaisin edelliselle sivulle ilman validointia

KEHFORM-778

---

src/configToSchemas/types/consent.js

KEHFORM-861

---

src/useLocalizeErrors.js

Fix form group errors

---

src/configToSchemas/types/number.js

Use number default

---

src/Review/types/boolean.js
src/configToSchemas/types/consent.js

Suostumus kentän bugikorjaukset

KEHFORM-872

---

src/configToSchemas/types/bmi.js
src/configToSchemas/types/consent.js
src/configToSchemas/types/title.js
src/withSteps.js

Accessibility headers fixes

---

src/RichText/index.js
src/configToSchemas/types/richtext.js
src/configToSchemas/types/text.js
src/useLocalizeErrors.js
src/withSteps.js

Monisivuisen kyselyn validointi aina eteenpäin mentäessä
Numero ja tekstikenttien validointi tyhjänä

KEHFORM-860

---

src/Review/types/boolean.js

Stacktrace korjaus suostumuskentässä
Toistettavuuden disablointi suostumuskentässä

KEHFORM-885

---

src/useDynamicElements.js

Disable elements

---

src/configToSchemas/types/multiselect.js
src/configToSchemas/types/select.js
src/utils.js

Fix autosort choices

---

lang/en-US.json
lang/sv-SE.json
src/withSteps.js

Monisivuisen lomakkeen review korjaus
Kielistys eteenpäin napille

KEHFORM-894

---

src/configToSchemas/types/date/index.js
src/configToSchemas/types/dateRange/index.js

Päivämäärä ja haarukka tyyppisen kysymyksen rajoitusten parannusta
Lisävalinta "ei rajoitusta"

KEHFORM-897

---

lang/en-US.json
lang/sv-SE.json
src/Review/Field.js
src/configToSchemas/commonPlugins/repeatableFieldSupport.js
src/configToSchemas/types/compose.js
src/configToSchemas/types/index.js

Composed field

---

src/Formula.js
src/withLiveValidateOnError.js
src/withSteps.js

[KEHFORM-812](https://jira.vismaconsulting.fi/browse/KEHFORM-812)

LiveValidateOnError and fixes

---

src/configToSchemas/types/compose.js

Compose fixes

---

src/Review/types/object.js
src/configToSchemas/types/tableField.js

Taulukon lähetyksen ja esikatselun stacktrace korjaus

KEHFORM-913

---

src/configToSchemas/types/boolean.js
src/configToSchemas/types/consent.js

Suostumus ja totuusarvo kysymysten kuvaustekstin näkyvyys korjaus

KEHFORM-845

---

src/useDynamicElements.js
src/useLocalizeErrors.js
src/utils.js

Fix validation when there are elements with visibility restrictions

---

lang/en-US.json
lang/sv-SE.json
src/configToSchemas/types/dateRange/index.js
src/useLocalizeErrors.js

Päivämäärähaarukan pakollisuuden toteutus

KEHFORM-898

---

src/configToSchemas/types/date/index.js

KEHFORM-635

---

lang/en-US.json
lang/sv-SE.json
src/Formula.js
src/configToSchemas/types/text.js
src/withCustomValidation.js

Validation functions

---

src/configToSchemas/commonPlugins/repeatableFieldSupport.js
src/useLocalizeErrors.js

Repeatable field validation

---

lang/en-US.json
lang/sv-SE.json
src/ConfirmDialog.js
src/ErrorFallback.js
src/Formula.js
src/withConfirmSubmit.js
src/withFormulaErrorBoundary.js

[KEHFORM-569](https://jira.vismaconsulting.fi/browse/KEHFORM-569)

Error handling

---

src/Formula.js
src/withScrollToError.js

Scrolling to validation error list

---

lang/en-US.json
lang/sv-SE.json
src/configToSchemas/types/number.js

Kokonaisluku kentän nimen vaihto "Numero" kentäksi

KEHFORM-856

---

src/configToSchemas/types/richtext.js

Rikastetun tekstikentän oletusarvo

KEHFORM-1001

---

src/configToSchemas/types/text.js

Lisätty ehdollisuuksia minLegth ja pattern validointeihin, ettei tulisi kahta samaa tarkoittavaa virheviestiä kerralla.

KEHFORM-906

---

lang/en-US.json
lang/sv-SE.json
src/configToSchemas/types/tableField.js
src/withCustomValidation.js

[KEHFORM-886](https://jira.vismaconsulting.fi/browse/KEHFORM-886)

Tablefield required validator

---

src/useLocalizeErrors.js

Fix missing pattern errors when text field is repeatable

---

lang/en-US.json
lang/sv-SE.json
src/configToSchemas/typePlugins/formGroupList.js
src/withCustomValidation.js

Duplicate key validation

---

lang/en-US.json
lang/sv-SE.json
src/configToSchemas/types/email.js
src/configToSchemas/types/text.js

Email regex validation

---

src/RichText/index.js

Richtext fix

---

src/Review/types/array.js
src/Review/types/string.js

Inline review

---

src/withCustomValidation.js

Null check for adding errors

---

src/configToSchemas/types/compose.js

Odottamaton virhe lisättäessä toistettava valintakysymys koottuun kenttään

KEHFORM-1045

---

src/useLocalizeConfig.js
src/useLocalizeErrors.js

Lisätty kenttä "Virheviestissä esitettävä otsikko" erillisen otsikon alle

KEHFORM-914

---

lang/en-US.json
lang/sv-SE.json
src/useLocalizeErrors.js

Tyhjän valintalistan validointi

KEHFORM-802

---

lang/en-US.json
lang/sv-SE.json
src/useLocalizeErrors.js

Virheviestien selkeyttäminen tiedostotyyppisessä kysymyksessä

KEHFORM-758

---

src/Review/types/string.js

Otsikon ja leipätekstin näkyvyyden korjaus lomakkeen lähetyksen jälkeen ja esikatselussa

KEHFORM-1031

---

src/configToSchemas/commonPlugins/repeatableFieldSupport.js

No support for repeatability of certain fields

---

src/withCustomValidation.js

Formgroup list validation

---

src/configToSchemas/types/date/index.js

Date field fixes

---

lang/en-US.json
lang/sv-SE.json
src/configToSchemas/types/bmi.js

Bmi field keys

---

src/configToSchemas/types/dateRange/index.js

Lisätty puuttuvia kuvaustekstejä päivämäärähaarukkaan, totuusarvoon ja valinta kysymykseen.

KEHFORM-1056

---

src/withCustomValidation.js

Formgroup custom validation missing formData

KEHFORM-1084

---

src/configToSchemas/index.js
src/withScrollToError.js
src/withSteps.js

Changed document-object references

KEHFORM-1065

---

src/configToSchemas/types/tableField.js

KEHFORM-1080

---

lang/en-US.json
lang/sv-SE.json
src/configToSchemas/types/formGroup.js
src/useLocalizeErrors.js

Require at least one

---

src/ConfirmDialog.js
src/withConfirmSubmit.js

- Append dialog elements inside form instead of document.body

Fix confirm dialog styles in embedded environment

---

lang/en-US.json
lang/sv-SE.json
src/ConfirmDialog.js
src/Markdown.js
src/configToSchemas/types/date/style.css
src/configToSchemas/types/dateRange/style.css

Datepickerin css korjauksia, kielistys virheitä ja avatun linkin css muutos

KEHFORM-1088

---

src/withScrollToError.js
src/withSteps.js

Automatic scrolling

---

src/configToSchemas/types/date/index.js
src/configToSchemas/types/dateRange/index.js

Päivämäärä kalenteri muutettu näyttämään vain yksi kuukausi ja tehty haarukka elementistä kompaktimpi

KEHFORM-1117

---

src/Review/types/object.js

Fix formGroup visible fields in review

---

src/Review/index.js
src/configToSchemas/types/date/style.css
src/configToSchemas/types/dateRange/style.css

CSS korjauksia ja reviewProppeihin arvo showSuccessText

KEHFORM-1141

---

src/Review/index.js

Summary before answers

---

README.md
src/Review/index.js

Added reviewprop for success text highlighting.
Updated readme with code examples.

KEHFORM-1163

---

src/configToSchemas/types/stepTitle.js
src/configToSchemas/types/title.js
src/withSteps.js

Add disabling steps with fillProps

---

src/ConfirmDialog.js
src/Review/index.js
src/withConfirmSubmit.js

[KEHFORM-1176](https://jira.vismaconsulting.fi/browse/KEHFORM-1176)

Custom messages

---

src/configToSchemas/types/select.js

Add scores to select fields

---

src/Review/index.js
src/Review/types/string.js

-Lisätty numerointi ja väliä yläpuolella olevaan elementtiin lomakkeen esikatselun sivuotsikoihin 
-Korjattu sivuotsikoiden fonttikoko

KEHFORM-1193

---

src/withSteps.js

Monisivuisen lomakkeen sivunvaihdon scrollauksen korjausta

KEHFORM-1195

---

src/withConfirmSubmit.js

Wrap form into div that hides form when printing

---

src/configToSchemas/commonPlugins/fieldTitleSupport.js

Logon lisäys mahdollisuus lomake editorissa

KEHFORM-1221

---

src/configToSchemas/types/formGroup.js

HandleFalseAsUndefined

---

src/configToSchemas/types/body.js
src/configToSchemas/types/compose.js
src/configToSchemas/types/consent.js
src/configToSchemas/types/image.js
src/configToSchemas/types/stepTitle.js
src/configToSchemas/types/title.js

Additional types to help validation

---

src/useDynamicElements.js

Fix disappearing formgroup data

---

src/Review/types/object.js
src/Review/types/string.js

Dateformat props

---

src/useDynamicElements.js

Hide step elements

---

lang/en-US.json
lang/sv-SE.json
src/useLocalizeErrors.js

[KEHFORM-1235](https://jira.vismaconsulting.fi/browse/KEHFORM-1235)

AnyOf error formatting

---

src/configToSchemas/types/boolean.js
src/configToSchemas/types/consent.js

[KEHFORM-1201](https://jira.vismaconsulting.fi/browse/KEHFORM-1201), [KEHFORM-1205](https://jira.vismaconsulting.fi/browse/KEHFORM-1205)

Accessibility components and required

---

src/configToSchemas/types/bmi.js
src/configToSchemas/types/date/index.js
src/configToSchemas/types/dateRange/index.js
src/utils.js

[KEHFORM-1201](https://jira.vismaconsulting.fi/browse/KEHFORM-1201)

Accessibility required labels

---

api.json
src/api.js
src/withConfirmSubmit.js

Use layers in submission

---

src/Review/Field.js
src/Review/types/array.js
src/useDynamicElements.js

[KEHFORM-818](https://jira.2day.fi/browse/KEHFORM-818) and [KEHFORM-817](https://jira.2day.fi/browse/KEHFORM-817)

Incremental indentation

---

src/configToSchemas/commonPlugins/repeatableFieldSupport.js

[KEHFORM-1266](https://jira.2day.fi/browse/KEHFORM-1266)

Extra list options

---

src/configToSchemas/types/date/index.js
src/configToSchemas/types/dateRange/index.js

[KEHFORM-1248](https://jira.2day.fi/browse/KEHFORM-1248)

DateFormat when filling forms

---

package.json

Reverts Visma-Consulting/formula#175

Revert "KEHFORM-1108: New datepicker component"

---

src/configToSchemas/types/multiselect.js

[KEHFORM-1295](https://jira.2day.fi/browse/KEHFORM-1295)

Multichoice scores

---

src/configToSchemas/types/date/index.js

Date defaults

---

src/Review/Field.js
src/Review/index.js
src/Review/types/string.js

[KEHFORM-1298](https://jira.2day.fi/browse/KEHFORM-1298)

Review upgrades

---

src/useDynamicElements.js

Disable reset formdata

---

src/Review/Field.js
src/Review/types/string.js

Review header levels

---

src/Review/Field.js

[KEHFORM-1312](https://jira.2day.fi/browse/KEHFORM-1312)

Form review hr

---

src/useLocalizeErrors.js

Fix repeatable formgroup error messages

---

lang/en-US.json
lang/sv-SE.json
src/Review/types/string.js

Change range review

---

src/configToSchemas/types/bmi/bmi.js

Calculate child bmi by dates

---

src/withFillActions.js

Fix withFillActions and withDraftSave

---

src/configToSchemas/types/formGroup.js

Remove filtered fields from validation

---

lang/en-US.json
lang/sv-SE.json
src/configToSchemas/types/text.js

[KEHFORM-1332](https://jira.2day.fi/browse/KEHFORM-1332)

Y-tunnus validointi

---

src/withDraftSave.js

Draft save with layers

---

lang/en-US.json
lang/sv-SE.json
src/withSteps.js

[KEHFORM-1197](https://jira.2day.fi/browse/KEHFORM-1197)

Accessibility withSteps

---

lang/en-US.json
lang/sv-SE.json
src/utils.js
src/withCustomValidation.js

[KEHFORM-438](https://jira.2day.fi/browse/KEHFORM-438)

Duplicate key validator

---

lang/en-US.json
lang/sv-SE.json
src/ConfirmDialog.js
src/Formula.js
src/withRecaptcha.js

[KEHFORM-1296](https://jira.2day.fi/browse/KEHFORM-1296)

Move recaptcha to form

---

src/api.js
src/configToSchemas/types/button.js

KEHFORM-1102: Mahdollisuus luoda uusia kysymyksiä kyselyn ja kysymysryhmän muokkaus -näkymässä

---

src/configToSchemas/typePlugins/formGroupList.js

Validate element keys

---

lang/en-US.json
lang/sv-SE.json
src/ConfirmDialog.js
src/Review/index.js
src/Review/types/object.js

[KEHFORM-1402](https://jira.2day.fi/browse/KEHFORM-1402)

Review only answered

---

src/RichText/index.js
src/configToSchemas/types/boolean.js
src/configToSchemas/types/consent.js
src/configToSchemas/types/date/index.js
src/configToSchemas/types/dateRange/index.js
src/configToSchemas/types/tableField.js

[KEHFORM-1211](https://jira.2day.fi/browse/KEHFORM-1211)

Accessibility audit fixes

---

src/useDynamicElements.js

[KEHFORM-1410](https://jira.2day.fi/browse/KEHFORM-1410)

Remove hidden formdata

---

src/configToSchemas/typePlugins/selectAutocomplete.js
src/configToSchemas/types/date/index.js
src/configToSchemas/types/tableField.js

Aria-describedby

---

package.json
src/ConfirmDialog.js
src/withRecaptcha.js

Invisible recaptcha

---

src/configToSchemas/types/number.js

NumberOfDecimals

---

api.json
src/api.js
src/withDraftSave.js

Send credentials

---

src/configToSchemas/types/compose.js

Underscore fixes

---

src/configToSchemas/typePlugins/selectAutocomplete.js
src/configToSchemas/types/dateRange/index.js

Accessibility reading error messages

---

src/configToSchemas/typePlugins/formGroupList.js

Editor elements pagination

---

lang/en-US.json
lang/sv-SE.json
package.json
src/Review/types/object.js
src/configToSchemas/types/calcTable.js
src/configToSchemas/types/index.js
src/configToSchemas/types/tableField.js
src/useLocalizeConfig.js
types/index.ts

Calc table + table rows

---

lang/en-US.json
lang/sv-SE.json
src/Review/Field.js
src/Review/types/object.js
src/configToSchemas/types/confirmField.js
src/configToSchemas/types/index.js
src/useLocalizeConfig.js
src/withCustomValidation.js

Sähköposti vahvistuksella
